### ISSUE TITLE
install.sh fails on macOS

### ISSUE THREAD

**Issue by brandazzle** [olback/library-loader#64]
On MacOS Big Sur, after running all prior build-from-source steps successfully, attempting `sudo ./install.sh` gives
`cp: /usr/bin/library-loader-gui: Operation not permitted`
`cp: directory /usr/share/applications does not exist`
`cp: /usr/share/icons/hicolor/scalable/apps/net.olback.LibraryLoader.svg: No such file or directory`
This appears to be because the `install.sh` is designed for Linux.

**Comment by brandazzle** [comment]
I've managed to run the GUI app successfully by just running the `library-loader-gui` executable directly; however, it clearly cannot access its assets, since the window minimize and close buttons aren't rendering properly at all.

**Comment by olback** [comment]
The `install.sh` is indeed designed for Linux. I wish I could provide a better Mac experience but since I don't actually have one, it's rather difficult.

The icon issue may be fixed if you install the Adwaita icon pack [(adwaita-icon-theme)](https://formulae.brew.sh/formula/adwaita-icon-theme) via homebrew.

**Comment by olback** [comment]
Closing in favor of #67
